### ISSUE TITLE
How to integrate with the colors scheme?

### ISSUE THREAD

**Issue by metaxy** [digitaldeacon/vue-sermons#4]
EBTC has a different one than ecg.

Reicht Bootstrap da nicht aus?

# CSS Classes
`.color-primary` `.color-accent` usw, aber dann vielleicht auch mit Gewichten, also `.color-primary-500`

Das würde aber dann mehr und mehr in die Richtung: http://tachyons.io/ mutieren.

# Configuration im Backend
Aber dafür müsste ich dann das CSS dynamisch generieren

**Comment by metaxy** [comment]
Eine extra CSS sollte aber sowieso das ganze Design überschreiben können. Also wäre SASS eine Option als Template, das man modifizieren kann und dann einfach einbindet.

**Comment by metaxy** [comment]
4px rundung für ebtc

**Comment by axtho** [comment]
Eine gut durchdachtes schema der Klassen für die einzelnen Elemente wäre notwendig, dann lässt sich das ganz einfach per css aus WP raus überschreiben.

**Comment by metaxy** [comment]
done
